
<section id="portfolio" class="bg-light-gray" <?php echo $hidden;?>>
    <div class="container">
        
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Confirma a exclusão abaixo?</h2>
                <h3 class="section-subheading text-muted">Após apagar, não poderá ser recuperado as informações correspondestes ao ítem.</h3>
            </div>
        </div>
               
        <div class="row">
            <div class="row">
                <form action="<?php echo $this->url('configuracoes/del-servico',array('action'=>'delServico'));?>" method="post">
                    <div class="col-md-12 col-sm-6 portfolio-item">
                        <a href="#" class="portfolio-link" data-toggle="modal">
                            <!--<img src="<?php //echo $this->basePath();?>/img/fotos/<?php //echo $id.'/'.$id_foto; ?>.jpg" class="img-responsive"  alt="">-->
                        </a>
                        <input type="hidden" name="id-servico" value="<?php echo $servico['id']?>" />
                        <div class="portfolio-caption">
                            
                            <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x text-primary"></i>
                                <i class="fa <?php echo $servico['faicon'];?> fa-stack-1x fa-inverse"></i>
                            </span>
                            <h4 class="service-heading"><?php echo $servico['titulo'];?></h4>
                            <p class="text-muted"><?php echo $servico['descricao'];?></p>
                            <br/>
                            <input type="submit" class="btn btn-info" value="Confirmar">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a class="btn btn-danger" href="<?php echo $this->url('configuracoes/default',array('action'=>'index')); ?>">
                                <i class="fa fa-trash-o" aria-hidden="true"></i> Cancelar
                            </a>
                            <p class="text-muted"> </p>
                        </div>
                    </div>
                </form>    
            </div>
        </div>
    </div>
</section>

<?php if(!is_null($saida)){
    echo '<section id="">
        <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">'.$saida
            . '<a class="btn btn-xl" href="'. $this->url('configuracoes/default',array('action'=>'index')).'">
                             Continuar
                        </a>
            </div></div></div></section>' ;} ?>
