<?php echo $this->doctype() ?>
<head>
<meta http-equiv="content-language" content="pt-br">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html" charset="utf-8">

<title>Nortes</title>

<!-- Bootstrap Core CSS -->
<?php  echo $this->headLink()->appendStylesheet($this->basePath(). '/css/bootstrap.min.css' , 'screen')?>
<!-- Custom CSS -->
<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/agency.css' , 'screen')?>
<!-- Custom Fonts -->
<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css' , 'screen')?>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header page-scroll">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
			 <div class="timeline-image">
                   <img class="img img-responsive" src="<?php echo $this->basePath(). '/img/logos/nortes.png'?>" alt="">
             </div>
            
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="hidden"><a href="#page-top"></a></li>
					<li><a class="page-scroll" href="<?php echo $this->url('inicio/default', array('action' => 'index'/*, 'id' => 1*/))?>">Inicio</a></li>
					<li><a class="page-scroll" href="<?php echo $this->url('portfolio/default',array('action'=>'index'))?>">Portfólio</a></li>
					<li><a class="page-scroll" href="<?php echo $this->url('sobre/default',array('action'=>'sobre'))?>">Sobre</a></li>
					<!--<li><a class="page-scroll" href="<?php echo $this->url('time/default',array('action' => 'time'))?>">Time</a></li>-->
					<li><a class="page-scroll" href="<?php echo $this->url('contato/default',array('action' => 'contato'))?>">Orçamento</a></li>
					<li><a class="page-scroll" href="#">Portal EDUCA</a></li>
					<li>
					<a class="page-scroll " href="<?php echo $this->url('login/default',array('action'=>'login'))?>">
						<span class="fa-stack fa-1x">                     
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    </li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>

            <?php echo $this->content; ?>
        
        
        <?php //echo $this->inlineScript() ?>
    
            
    
    <!-- jQuery -->
    <script src="<?php echo $this->basePath(). '/js/jquery.js'; ?>"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->basePath().'/js/bootstrap.min.js' ?>"></script>

    <!-- Plugin JavaScript 
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>-->

    <!-- Contact Form JavaScript 
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>
    -->

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo $this->basePath().'/js/agency.js' ?>"></script>    
    <footer class="">
		<!--<footer class="navbar-fixed-bottom">-->
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Your Website 2014</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>    
</body>

</html>