-- MySQL Script generated by MySQL Workbench
-- 07/21/16 23:30:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema douglas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema douglas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `douglas` DEFAULT CHARACTER SET utf8 ;
USE `douglas` ;

-- -----------------------------------------------------
-- Table `douglas`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `douglas`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `douglas`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `douglas`.`portfolio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `douglas`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `douglas`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` LONGTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `portfolio_id` INT NOT NULL,
  `capa` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `portfolio_id`),
  INDEX `fk_descricao_portfolio_idx` (`portfolio_id` ASC),
  CONSTRAINT `fk_descricao_portfolio`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `douglas`.`portfolio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
