<section id="contact">

      
<div class="pricing-area text-center">
    <div class="row">
        <div class="col-sm-6 col-md-3 plan price-four wow fadeInDown">
                            <ul>
                                <li class="heading-four">
                                    <h1>Basic</h1>
                                    <span>$3/Month</span>
                                </li>
                                <li>5 Gb Disk Space</li>
                                <li>1GB Dadicated Ram</li>
                                <li>10 Addon Domain</li>
                                <li>10 Email Account</li>
                                <li>24/7 Support</li>
                                <li class="plan-action">
                                    <a href="" class="btn btn-primary">Sign up</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-sm-6 col-md-3 plan price-five wow fadeInDown">
                            <ul>
                                <li class="heading-five">
                                    <h1>Standerd</h1>
                                    <span>$6/Month</span>
                                </li>
                                <li>5 Gb Disk Space</li>
                                <li>1GB Dadicated Ram</li>
                                <li>10 Addon Domain</li>
                                <li>10 Email Account</li>
                                <li>24/7 Support</li>
                                <li class="plan-action">
                                    <a href="" class="btn btn-primary">Sign up</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-sm-6 col-md-3 plan price-six wow fadeInDown">
                             <img src="images/ribon_two.png">
                            <ul>
                                <li class="heading-six">
                                    <h1>Premium</h1>
                                    <span>$12/Month</span>
                                </li>
                                <li>5 Gb Disk Space</li>
                                <li>1GB Dadicated Ram</li>
                                <li>10 Addon Domain</li>
                                <li>10 Email Account</li>
                                <li>24/7 Support</li>
                                <li class="plan-action">
                                    <a href="" class="btn btn-primary">Sign up</a>
                                </li>
                            </ul>
                        </div>

                         <div class="col-sm-6 col-md-3 plan price-seven wow fadeInDown">
                            <ul>
                                <li class="heading-seven">
                                    <h1>Developer</h1>
                                    <span>$19/Month</span>
                                </li>
                                <li>5 Gb Disk Space</li>
                                <li>1GB Dadicated Ram</li>
                                <li>10 Addon Domain</li>
                                <li>10 Email Account</li>
                                <li>24/7 Support</li>
                                <li class="plan-action">
                                    <a href="" class="btn btn-primary">Sign up</a>
                                </li>
                            </ul>
                        </div>
    </div>
</div>
    
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Contact Us</h2>
                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button type="submit" class="btn btn-xl">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>