<section id="">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                

                <form action="<?php echo $this->basePath('portfolio/add', array('action'=>'add'));?>" method="post" enctype="multipart/form-data" <?php echo $hidden; ?>>                
                <h4 class="service-heading">Seleciona os arquivos</h4>
                <center>
                    <input type="hidden" name="titulo" value="<?php echo $titulo; ?>">
                    <input type="file" name="photos[]" class="btn btn-xl text-center" multiple="multiple" required="required">                    <br/>
                    <input type="submit" name="submit" class="btn btn-xl" value="Enviar">                </center>
                    </form>
                    
                    <?php print $saida; ?>
       
            </div>
        </div>
    </div>

</section>