<section id="">
        <div class="container">
            <div class="row">
	            <div class="col-lg-12 text-center">
	                    <h2 class="section-heading">Selecione</h2>
	                    <h3 class="section-subheading text-muted"> </h3>
	             </div>
            </div>
            <div class="row text-center">
            	<div class="col-md-12">
                    <a href="<?php echo $this->url('portfolio/titulo',array('action'=>'add'))?>">
	                    <span class="fa-stack fa-4x">
	                        <button type="submit" class="btn-painel-login fa fa-circle fa-stack-2x text-primary"></button>
	                        <button type="submit" class="btn-painel-login fa fa-th-large fa-stack-1x fa-inverse"></button>
	                    </span>
	                    <h4 class="service-heading" >Portfólio</h4>
                    </a>
                    <p></p>
                </div>
                <!--<div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <button class="btn-painel-login fa fa-circle fa-stack-2x text-primary"></button>
                        <button class="btn-painel-login fa fa-sitemap fa-stack-1x fa-inverse"></button>
                    </span>
                    <h4 class="service-heading">Time</h4>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <button class="btn-painel-login fa fa-circle fa-stack-2x text-primary"></button>
                        <button class="btn-painel-login fa fa-user fa-stack-1x fa-inverse"></button>
                    </span>
                    <h4 class="service-heading">Sobre</h4>
                    <p></p>
                </div>
            </div>-->
            <!--  <input name="uploads[]" type=file multiple />-->
        </div>
     </div>    
</section>
