
<section id="portfolio" class="bg-light-gray" <?php echo $hidden;?>>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Confirma a exclusão abaixo?</h2>
                <h3 class="section-subheading text-muted">Após apagar, não poderá ser recuperado as informações correspondestes ao ítem.</h3>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <form action="<?php echo $this->url('portfolio/default',array('action'=>'apagar-portfolio'));?>" method="post">
                    <div class="col-md-12 col-sm-6 portfolio-item">
                        <a href="#" class="portfolio-link" data-toggle="modal">
                            <img src="<?php echo $this->basePath();?>/img/fotos/<?php echo $id.'/'.$id_foto; ?>.jpg" class="img-responsive"  alt="">
                        </a>
                        <input type="hidden" name="id-portfolio" value="<?php echo $id?>" />
                        <div class="portfolio-caption">
                            <h4><?php echo $titulo ?></h4><br/>
                            <input type="submit" class="btn btn-info" value="Confirmar">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a class="btn btn-danger" href="<?php echo $this->url('login/default',array('action'=>'login')); ?>">
                                <i class="fa fa-trash-o" aria-hidden="true"></i> Cancelar
                            </a>
                            <p class="text-muted"> </p>
                        </div>
                    </div>
                </form>    
            </div>
        </div>
    </div>
</section>

<?php if(!is_null($saida)){
    echo '<section id="">
        <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">'.$saida
            . '<a class="btn btn-xl" href="'. $this->url('login/default',array('action'=>'login')).'">
                             Continuar
                        </a>
            </div></div></div></section>' ;} ?>
