
<section id="portfolio" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Portfolio</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
        </div>
        <div class="row">
            <?php 
            $portf = array();
            foreach ($portfolios as $portfolio):
                array_push($portf, $portfolio);
            endforeach;
            $qtd = count($portf); $k=0;  $j=0;
            $qtd_rows = ($qtd/ 3); $qtd_rows = ceil($qtd_rows);
            ?>
        <?php do{?>
            <div class="row">
              <?php for($i=0; $i<3;$i++){
                  if(!empty($portf[$k]['id'])) {?>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal<?php echo $portf[$k]['id'] ?>" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="<?php echo $this->basePath();?>/img/fotos/<?php echo $portf[$k]['id'] ?>/0.jpg" class="img-responsive"  alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4><?php echo $portf[$k]['nome'] ?></h4>
                        <p class="text-muted"> </p>
                    </div>
                </div>
              <?php $k++;}} ?>
            </div>
        <?php $j++; }while($j < $qtd_rows); ?>
        </div>
        <center>
            <ul class="pagination pagination-lg">
                <li><a href="#"><i class="fa fa-long-arrow-left"></i></a></li>
                <li class=""><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">..</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#"><i class="fa fa-long-arrow-right"></i></a></li>
            </ul><!--/.pagination-->
        </center>
        <?php
        $id_fotos = array();
        $fotos_array = array();
        foreach ($fotos as $f) :
            array_push($id_fotos, (int) $f['portfolio_id']);
            array_push($fotos_array, $f);
        endforeach;
        $id_fotos = array_count_values($id_fotos);
        $j=0; $id=0;
        foreach ($fotos_array as $foto) :
            if($id!=$foto['portfolio_id']) {?>                    
            <div class="portfolio-modal modal fade" id="portfolioModal<?php echo $foto['portfolio_id']; ?>" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-content">
                    <div class="close-modal" data-dismiss="modal">
                        <div class="lr">
                            <div class="rl">
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-lg-offset-2">
                                <?php
                                $id = $foto['portfolio_id'];
                                for($i = 0; $i < $id_fotos[$id];$i++){
                                ?>
                                <div class="modal-body">
                                    <!-- Project Details Go Here -->
                                    <h2><?php echo $fotos_array[$j]['nome']; ?></h2>
                                    <!--<p class="item-intro text-muted"><?php //echo $foto['nome']; ?></p>-->
                                    <img class="img-responsive" src="<?php echo $this->basePath();?>/img/fotos/<?php echo $fotos_array[$j]['portfolio_id'] . '/' . $i; ?>.jpg" alt="">
                                    <p><?php echo $fotos_array[$j]['descricao']; ?></p>
                                </div>
                                <?php $j++;}?>
                                    <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php }endforeach;?>
    </div>
</div>
</section>
