<section id="">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">

                <form action="<?php echo $this->basePath('portfolio/add', array('action' => 'titulo')); ?>" method="post" enctype="multipart/form-data">                
                    <h4 class="service-heading">Informe o título</h4>
                    <center>
                        <div class="form-group">                            
                        <i class="fa fa-check fa-stack-2x text-primary"></i>
                        <input type="text" name="titulo" class="titulo-text" placeholder="Informe o Título do Portfólio" maxlength="45" id="titulo" required data-validation-required-message="Please enter your name.">
                        </div>
                        <input type="submit" name="submit" class="btn btn-xl" value="Enviar">
                    </center>
                </form>

            </div>
        </div>
    </div>

</section>